blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogDeleteView, BlogCreateView, BlogUpdateView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='index'),
    path('post/<int:pk>', BlogDetailView.as_view(), name='post'),
    path('post/<int:pk>/delete', BlogDeleteView.as_view(), name='delete_post'),
    path('create', BlogCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update', BlogUpdateView.as_view(), name='update_post')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


# Create your models here.

class Blog(models.Model):
    """
    Модель блоговой записи
    """
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='Slug')
    text = models.TextField(verbose_name='Cодержимое')
    image = models.ImageField(upload_to='blog_image', verbose_name='Превью')
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    is_active = models.BooleanField(verbose_name='Признак публикации', default=True)
    views_count = models.PositiveIntegerField(verbose_name='Количество просмотров', default=0)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'пост для блога'
        verbose_name_plural = 'посты для блога'

blog/forms.py
from django import forms
from blog.models import Blog


class FormControlMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'image', 'is_active')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from pytils.templatetags.pytils_translit import slugify
from blog.forms import BlogForm
from blog.models import Blog
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView


# Create your views here.


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_queryset(self):
        posts = super().get_queryset()
        hidden = self.request.GET.get('hidden')
        if not hidden:
            posts = posts.filter(is_active=True)
        return posts

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        hidden = self.request.GET.get('hidden')
        if hidden:
            data['hidden'] = True
        return data


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    success_url = reverse_lazy('blog:index')
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    success_url = reverse_lazy('blog:index')
    form_class = BlogForm

    def get_success_url(self):
        return reverse('blog:post', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:index')

blog/templates/blog/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Блог{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% block content %}{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% include 'blog/includes/header_delete_blog.html' %}
        <div class="my-2">
            <div class="card border-warning mb-3 text-center">
                <div class="card-header">Вы точно хотите удалить?</div>
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.text|slice:":100" }}...</p>
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a class="btn btn-secondary" href="{% url 'blog:index' %}">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% include 'blog/includes/header_blog.html' %}
        <div class="my-2">
            <div class="card mb-3" style="max-width: 100em;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{% mymedia object.image %}" class="img-fluid rounded-start"
                             alt="image for {{ object.name }}">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            {% if perms.is_superuser or request.user|has_group:"blog_content_manager" %}
                            <div class="my-4">
                                <a href="{% url 'blog:update_post' object.id %}" type="button" class="btn btn-warning">Редактировать</a>
                            </div>
                            {% endif %}
                            {% if perms.is_superuser or request.user|has_group:"blog_content_manager" %}
                            <div class="my-4">
                                {% if object.is_active %}
                                <h3>{{ object.title }} <span class="badge text-bg-success">active</span></h3>
                                {% else %}
                                <h3>{{ object.title }} <span class="badge text-bg-danger">hidden</span></h3>
                                {% endif %}
                            </div>
                            {% else %}
                            <div class="my-4">
                                <h3>{{ object.title }}</h3>
                            </div>
                            {% endif %}
                            <div>{{ object.text }}</div>
                            <div class="my-4">
                                <p class="card-text">
                                    <small class="text-body-secondary">Просмотры: {{ object.views_count }}</small>
                                </p>
                                <p class="card-text">
                                    <small class="text-body-secondary">Дата публикации: {{ object.created_at }}</small>
                                </p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "catalog/base.html" %}
{% block title %}Add Post{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        <div class="bg-body-tertiary p-4 rounded">
            <div class="container my-3 col-8">
                <form class="row g-3" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if object %}
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary w-100 mt-4 mb-2">Cохранить</button>
                    </div>
                    {% else %}
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary w-100 mt-4 mb-2">Создать</button>
                    </div>
                    {% endif %}
                </form>
                <div class="col-12">
                    <a class="btn btn-secondary w-100" href="{% url 'blog:index' %}">Отмена</a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "blog/base.html" %}
{% load my_tags %}
{% block title %}Blog{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% include 'blog/includes/header_main.html' %}
        {% if perms.is_superuser or request.user|has_group:"blog_content_manager" %}
        <div class="row m-4">
            <div class="p-2 col-2">
                <a href="{% url 'blog:create_post' %}" class="btn btn-outline-primary">+ Добавить Пост +</a>
            </div>
            {% if hidden %}
            <div class="p-2 col-4">
                <a href="{% url 'blog:index' %}" class="btn btn-outline-secondary">Скрыть неопубликованные</a>
            </div>
            {% else %}
            <div class="p-2 col-4">
                <a href="{% url 'blog:index' %}?hidden=True" class="btn btn-outline-secondary">Показать неопубликованные</a>
            </div>
            {% endif %}
        </div>
        {% endif %}
        <div class="row m-4">
            {% for object in object_list %}
            <div class="p-2 rounded col-4">
                <div class="card m-4">
                    <img src="{% mymedia object.image  %}" class="card-img-top" alt="no_image">
                    <div class="card-body">
                        {% if perms.is_superuser or request.user|has_group:"blog_content_manager" %}
                        {% if object.is_active %}
                        <h5>{{ object.title }}   <span class="badge text-bg-success">active</span></h5>
                        {% else %}
                        <h5>{{ object.title }}   <span class="badge text-bg-danger">hidden</span></h5>
                        {% endif %}
                        {% else %}
                        <h5>{{ object.title }}</h5>
                        {% endif %}
                        <p class="card-text"><i>{{ object.slug }}</i></p>
                        <p class="card-text">{{ object.text|slice:99 }}...</p>
                        <a href="{% url 'blog:post' object.id %}" type="button" class="btn btn-primary">Открыть</a>
                        {% if perms.is_superuser or request.user|has_group:"blog_content_manager" %}
                        <a href="{% url 'blog:delete_post' object.id %}" type="button"
                           class="btn btn-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}