blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogDeleteView, BlogCreateView, BlogUpdateView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='index'),
    path('post/<int:pk>', BlogDetailView.as_view(), name='post'),
    path('post/<int:pk>/delete', BlogDeleteView.as_view(), name='delete_post'),
    path('create', BlogCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update', BlogUpdateView.as_view(), name='update_post')
]

catalog/urls.py
from django.urls import path
from catalog.views import (
    IndexListView,
    ContactCreateView,
    ThanxDetailView,
    ProductDetailView,
    ProductListView,
    AddProductCreateView,
    SuccessAddProductDetailView,
    ProductDeleteView,
    ProductUpdateView,
    SuccessDeleteTemplateView
)
from catalog.services import set_cache_controller

app_name = 'catalog'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('contacts/', ContactCreateView.as_view(), name='contacts'),
    path('product/<int:pk>/', set_cache_controller(ProductDetailView.as_view()), name="product"),
    path('products/', ProductListView.as_view(), name="products"),
    path('add_product/', AddProductCreateView.as_view(), name="add_product"),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name='delete_product'),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name='update_product'),
    path('success_delete_product/<int:pk>/', SuccessDeleteTemplateView.as_view(), name='success_delete_product'),
    path('success_adding_product/<int:pk>/', SuccessAddProductDetailView.as_view(), name="success_adding_product"),
    path('thanx/<int:pk>/', ThanxDetailView.as_view(), name='thanx')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user.views import RegisterCreateView, email_verification, reset_password, ProfileUpdateView

app_name = 'user'

urlpatterns = [
    path('', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('check_email/<str:token>/', email_verification, name='email_verification'),
    path('reset_password', reset_password, name='reset_password'),
    path('profile', ProfileUpdateView.as_view(), name='profile')
]

catalog/models.py
from django.db import models
from user.models import User


# Create your models here.

class Category(models.Model):
    """
    Модель для категорий
        name - Наименование
        description - Описание
    """
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=255, verbose_name='Описание')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'категории'


class Product(models.Model):
    """
    Модель для продуктов:
        name - Наименование
        description - Описание
        image - Изображение (превью)
        category - Категория
        price - Цена за покупку
        created_at - Дата создания (записи в БД)
        updated_at - Дата последнего изменения (записи в БД)
    """
    name = models.CharField(max_length=100, verbose_name='Наименование')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, verbose_name='Описание')
    image = models.ImageField(upload_to='product_image', verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    is_published = models.BooleanField(verbose_name='Признак публикации', default=False)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

        permissions = [
            ('set_published', 'Can publish product'),
            ('edit_description', 'Can edit description'),
            ('change_category_product', 'Can change category of product')
        ]


class StoreContacts(models.Model):
    """
    Модель для контактной информации магазина
    name - тип контактной информации (сайт, телефон, почта итд)
    link - как связаться (адрес, номер телефона, ссылки итд)
    """
    name = models.CharField(max_length=100, verbose_name='Тип связи')
    link = models.CharField(max_length=100, verbose_name='Ссылка как связаться')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class UserContacts(models.Model):
    """
    Модель для контактной информации обратной связи пользователей
        first_name - Имя пользователя
        last_name - Фамилия пользователя
        email - Электронная почта пользователя
    """
    first_name = models.CharField(max_length=100, verbose_name='Имя пользователя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия пользователя')
    email = models.CharField(max_length=100, verbose_name='Электронная почта пользователя')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = 'контакт пользователя'
        verbose_name_plural = 'контакты пользователя'


class Version(models.Model):
    """
    Модель для хранения версий продукта
    """
    product = models.ForeignKey(Product, verbose_name='Название продукта', on_delete=models.CASCADE, related_query_name='versions')
    count = models.PositiveIntegerField(verbose_name='Номер версии', default=1)
    version_name = models.CharField(max_length=255, verbose_name='Название версии')
    is_current = models.BooleanField(verbose_name='Признак текущей версии', default=True)

    def __str__(self):
        return f"version#{self.count}: {self.version_name}"

    class Meta:
        verbose_name = "версия продукта"
        verbose_name_plural = "версии продукта"

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class FormControlMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'description', 'price', 'image',)

    def clean(self):
        """
        Валидация названия и описания продукта на запрещенные слова
        """
        stop_words = (
            'казино',
            'криптовалюта',
            'крипта',
            'биржа',
            'дешево',
            'бесплатно',
            'обман',
            'полиция',
            'радар'
        )
        data = self.cleaned_data
        name = data['name']
        description = data['description']
        for sw in stop_words:
            if sw in name.lower():
                msg = f'В поле НАЗВАНИЕ ПРОДУКТА используется запрещенное слово: {sw}! Отредактируйте ввод'
                self.add_error("name", msg)
            if sw in description.lower():
                msg = f'В поле ОПИСАНИЕ ПРОДУКТА используется запрещенное слово: {sw}! Отредактируйте ввод'
                self.add_error("name", msg)

        return data


class VersionForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ModeratorProductForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'description', 'is_published')

    def clean(self):
        """
        Валидация названия и описания продукта на запрещенные слова
        """
        stop_words = (
            'казино',
            'криптовалюта',
            'крипта',
            'биржа',
            'дешево',
            'бесплатно',
            'обман',
            'полиция',
            'радар'
        )
        data = self.cleaned_data
        description = data['description']
        for sw in stop_words:
            if sw in description.lower():
                msg = f'В поле ОПИСАНИЕ ПРОДУКТА используется запрещенное слово: {sw}! Отредактируйте ввод'
                self.add_error("name", msg)
        return data

catalog/views.py
from django.contrib.auth.models import Permission
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from catalog.models import Category, Product, StoreContacts, UserContacts, Version
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, TemplateView

from catalog.services import get_categories


class IndexListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        data = super().get_queryset().filter(is_published=True).order_by('-created_at')
        return data[:3]


class ContactCreateView(CreateView):
    """
    Отображение статической информаци о контактах с магазином
    Добавление пользовательских данных в базу
    """
    model = UserContacts
    fields = ('first_name', 'last_name', 'email',)

    # добавим в контекст для отображения статических данных
    contact_info = StoreContacts.objects.all()
    extra_context = {
        'contacts': contact_info
    }

    def get_success_url(self):
        new_user_id = self.get_context_data()['object'].id
        return reverse('catalog:thanx', args=[new_user_id])


class ThanxDetailView(DetailView):
    model = UserContacts


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        """
        Переопределение метода запроса
        чтобы динамически фильтровать вывод товара по категориям
        """

        category_id = self.request.GET.get('category_id')
        data = super().get_queryset().order_by('-created_at')
        if category_id:
            data = data.filter(category_id=category_id).order_by('-created_at')
        return data

    def get_context_data(self, **kwargs):
        """
        Переопределение метода
        для добавления в контекст дополнительных объектов
        categories: список объектов категории для фильтрации продуктов
        category: текущая категория
        """
        category_id = self.request.GET.get('category_id')
        data = super().get_context_data()
        data['object_list'] = [{'product': item, 'version': item.version_set.filter(is_current=True).first()} for item in data['object_list']]
        data['categories'] = get_categories()
        data['category'] = get_object_or_404(Category, id=category_id) if category_id else None
        return data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class AddProductCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('user:login')
    model = Product
    template_name = 'catalog/product_form.html'
    form_class = ProductForm

    def get_success_url(self):
        new_product_id = self.get_context_data()['object'].id
        return reverse('catalog:success_adding_product', args=[new_product_id])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            data['formset'] = VersionFormset(self.request.POST)
        else:
            data['formset'] = VersionFormset()
        return data

    def form_valid(self, form):
        """
        Валидация
        Проверка на несколько текущих версий
        """
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            instances = formset.save(commit=False)
            check_update = [instance for instance in instances]
            for item in formset.queryset:
                if item not in check_update:
                    check_update.append(item)
            check_current = [item for item in check_update if item.is_current]
            if len(check_current) > 1:
                form.add_error(None, "Может быть только одна версия!")
                return self.form_invalid(form)
            else:
                form.instance.user = self.request.user
                self.object = form.save()
                formset.instance = self.object
                formset.save()
                return super().form_valid(form)
        return super().form_invalid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('user:login')
    model = Product
    success_url = reverse_lazy('catalog:products')


class SuccessDeleteTemplateView(TemplateView):
    template_name = 'catalog/success_delete_product.html'


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('user:login')
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            data['formset'] = VersionFormset(instance=self.object)
        return data

    def form_valid(self, form):
        """
        Валидация
        Проверка на несколько текущих версий
        """
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            instances = formset.save(commit=False)
            check_update = [instance for instance in instances]
            for item in formset.queryset:
                if item not in check_update:
                    check_update.append(item)
            check_current = [item for item in check_update if item.is_current]
            if len(check_current) > 1:
                form.add_error(None, "Может быть только одна версия!")
                return self.form_invalid(form)
            else:
                formset.instance = self.object
                formset.save()
                return super().form_valid(form)
        return super().form_invalid(form)

    def get_form_class(self):
        user = self.request.user
        moderator_permissions = [
            user.has_perm("catalog.set_published"),
            user.has_perm("catalog.edit_description"),
            user.has_perm("catalog.change_category_product")
        ]
        if self.object.user == user:
            return ProductForm
        if all(moderator_permissions):
            return ModeratorProductForm
        raise PermissionDenied


class SuccessAddProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/success_adding_product.html'

catalog/templates/catalog/includes/header_main.html
<div class="bg-body-tertiary p-4 rounded">
    <div class="col-sm-8 py-4 mx-auto">
        <h1 class="display-5 fw-medium">Local Farmers Store</h1>
        <p class="fs-5">Онлайн магазин фермерских продуктов</p>
        <p>онлайн-магазин свежих фермерских продуктов. Мы предлагаем натуральные и качественные товары прямо с фермы:
            свежие овощи, мясо, молоко, мед и многое другое. Поддержите местных производителей и наслаждайтесь настоящим
            вкусом природы, не выходя из дома.</p>
    </div>
</div>

catalog/templates/catalog/includes/header_product.html
<div class="bg-body-tertiary p-4 rounded">
    <div class="col-sm-8 py-4 mx-auto">
        <h1 class="display-5 fw-medium">Local Farmers Store</h1>
        <p class="fs-5">Онлайн магазин фермерских продуктов</p>
    </div>
</div>

catalog/templates/catalog/includes/header_products.html
<div class="bg-body-tertiary p-4 rounded">
    <div class="col-sm-8 py-4 mx-auto">
        <h1 class="display-5 fw-medium">Local Farmers Store</h1>
        {% if category %}
        <p class="fs-5">Продукты категории: {{ category.name }}</p>
        <p>{{ category.description }}</p>
        {% else %}
        <p class="fs-5">Все продукты</p>
        <p>Продукты из всех категорий</p>
        {% endif %}
    </div>
</div>

catalog/templates/catalog/includes/navbar_include.html
{% load my_tags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Offcanvas navbar large">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'catalog:index' %}">Local Farmers Store</a>
        {% if user.is_authenticated %}
        <p class="text-secondary"><small>вы вошли как:  </small><span class="badge text-bg-secondary">{{ user }}</span></p>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2"
                aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2"
             aria-labelledby="offcanvasNavbar2Label">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbar2Label">Offcanvas</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'catalog:index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'catalog:products' %}">Продукты</a>
                    </li>
                    {% if not request.user|has_group:"moderator" %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'blog:index' %}">Блог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'catalog:contacts' %}">Контакты</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    {% if not request.user|has_group:"moderator" and not request.user|has_group:"blog_content_manager" %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'catalog:add_product' %}">Добавить продукт</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'user:logout' %}">Выйти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'user:profile' %}">Профиль</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'user:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'user:register' %}">Регистрация</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>