blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogDeleteView, BlogCreateView, BlogUpdateView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='index'),
    path('post/<int:pk>', BlogDetailView.as_view(), name='post'),
    path('post/<int:pk>/delete', BlogDeleteView.as_view(), name='delete_post'),
    path('create', BlogCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update', BlogUpdateView.as_view(), name='update_post')
]

catalog/urls.py
from django.urls import path
from catalog.views import (
    IndexListView,
    ContactCreateView,
    ThanxDetailView,
    ProductDetailView,
    ProductListView,
    AddProductCreateView,
    SuccessAddProductDetailView,
    ProductDeleteView,
    ProductUpdateView,
    SuccessDeleteTemplateView
)
from catalog.services import set_cache_controller

app_name = 'catalog'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('contacts/', ContactCreateView.as_view(), name='contacts'),
    path('product/<int:pk>/', set_cache_controller(ProductDetailView.as_view()), name="product"),
    path('products/', ProductListView.as_view(), name="products"),
    path('add_product/', AddProductCreateView.as_view(), name="add_product"),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name='delete_product'),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name='update_product'),
    path('success_delete_product/<int:pk>/', SuccessDeleteTemplateView.as_view(), name='success_delete_product'),
    path('success_adding_product/<int:pk>/', SuccessAddProductDetailView.as_view(), name="success_adding_product"),
    path('thanx/<int:pk>/', ThanxDetailView.as_view(), name='thanx')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from user.models import User


# Create your models here.

class Category(models.Model):
    """
    Модель для категорий
        name - Наименование
        description - Описание
    """
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=255, verbose_name='Описание')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'категории'


class Product(models.Model):
    """
    Модель для продуктов:
        name - Наименование
        description - Описание
        image - Изображение (превью)
        category - Категория
        price - Цена за покупку
        created_at - Дата создания (записи в БД)
        updated_at - Дата последнего изменения (записи в БД)
    """
    name = models.CharField(max_length=100, verbose_name='Наименование')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, verbose_name='Описание')
    image = models.ImageField(upload_to='product_image', verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    is_published = models.BooleanField(verbose_name='Признак публикации', default=False)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

        permissions = [
            ('set_published', 'Can publish product'),
            ('edit_description', 'Can edit description'),
            ('change_category_product', 'Can change category of product')
        ]


class StoreContacts(models.Model):
    """
    Модель для контактной информации магазина
    name - тип контактной информации (сайт, телефон, почта итд)
    link - как связаться (адрес, номер телефона, ссылки итд)
    """
    name = models.CharField(max_length=100, verbose_name='Тип связи')
    link = models.CharField(max_length=100, verbose_name='Ссылка как связаться')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class UserContacts(models.Model):
    """
    Модель для контактной информации обратной связи пользователей
        first_name - Имя пользователя
        last_name - Фамилия пользователя
        email - Электронная почта пользователя
    """
    first_name = models.CharField(max_length=100, verbose_name='Имя пользователя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия пользователя')
    email = models.CharField(max_length=100, verbose_name='Электронная почта пользователя')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = 'контакт пользователя'
        verbose_name_plural = 'контакты пользователя'


class Version(models.Model):
    """
    Модель для хранения версий продукта
    """
    product = models.ForeignKey(Product, verbose_name='Название продукта', on_delete=models.CASCADE, related_query_name='versions')
    count = models.PositiveIntegerField(verbose_name='Номер версии', default=1)
    version_name = models.CharField(max_length=255, verbose_name='Название версии')
    is_current = models.BooleanField(verbose_name='Признак текущей версии', default=True)

    def __str__(self):
        return f"version#{self.count}: {self.version_name}"

    class Meta:
        verbose_name = "версия продукта"
        verbose_name_plural = "версии продукта"

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class FormControlMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'description', 'price', 'image',)

    def clean(self):
        """
        Валидация названия и описания продукта на запрещенные слова
        """
        stop_words = (
            'казино',
            'криптовалюта',
            'крипта',
            'биржа',
            'дешево',
            'бесплатно',
            'обман',
            'полиция',
            'радар'
        )
        data = self.cleaned_data
        name = data['name']
        description = data['description']
        for sw in stop_words:
            if sw in name.lower():
                msg = f'В поле НАЗВАНИЕ ПРОДУКТА используется запрещенное слово: {sw}! Отредактируйте ввод'
                self.add_error("name", msg)
            if sw in description.lower():
                msg = f'В поле ОПИСАНИЕ ПРОДУКТА используется запрещенное слово: {sw}! Отредактируйте ввод'
                self.add_error("name", msg)

        return data


class VersionForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ModeratorProductForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'description', 'is_published')

    def clean(self):
        """
        Валидация названия и описания продукта на запрещенные слова
        """
        stop_words = (
            'казино',
            'криптовалюта',
            'крипта',
            'биржа',
            'дешево',
            'бесплатно',
            'обман',
            'полиция',
            'радар'
        )
        data = self.cleaned_data
        description = data['description']
        for sw in stop_words:
            if sw in description.lower():
                msg = f'В поле ОПИСАНИЕ ПРОДУКТА используется запрещенное слово: {sw}! Отредактируйте ввод'
                self.add_error("name", msg)
        return data

catalog/views.py
from django.contrib.auth.models import Permission
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from catalog.models import Category, Product, StoreContacts, UserContacts, Version
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, TemplateView

from catalog.services import get_categories


class IndexListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        data = super().get_queryset().filter(is_published=True).order_by('-created_at')
        return data[:3]


class ContactCreateView(CreateView):
    """
    Отображение статической информаци о контактах с магазином
    Добавление пользовательских данных в базу
    """
    model = UserContacts
    fields = ('first_name', 'last_name', 'email',)

    # добавим в контекст для отображения статических данных
    contact_info = StoreContacts.objects.all()
    extra_context = {
        'contacts': contact_info
    }

    def get_success_url(self):
        new_user_id = self.get_context_data()['object'].id
        return reverse('catalog:thanx', args=[new_user_id])


class ThanxDetailView(DetailView):
    model = UserContacts


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        """
        Переопределение метода запроса
        чтобы динамически фильтровать вывод товара по категориям
        """

        category_id = self.request.GET.get('category_id')
        data = super().get_queryset().order_by('-created_at')
        if category_id:
            data = data.filter(category_id=category_id).order_by('-created_at')
        return data

    def get_context_data(self, **kwargs):
        """
        Переопределение метода
        для добавления в контекст дополнительных объектов
        categories: список объектов категории для фильтрации продуктов
        category: текущая категория
        """
        category_id = self.request.GET.get('category_id')
        data = super().get_context_data()
        data['object_list'] = [{'product': item, 'version': item.version_set.filter(is_current=True).first()} for item in data['object_list']]
        data['categories'] = get_categories()
        data['category'] = get_object_or_404(Category, id=category_id) if category_id else None
        return data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class AddProductCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('user:login')
    model = Product
    template_name = 'catalog/product_form.html'
    form_class = ProductForm

    def get_success_url(self):
        new_product_id = self.get_context_data()['object'].id
        return reverse('catalog:success_adding_product', args=[new_product_id])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            data['formset'] = VersionFormset(self.request.POST)
        else:
            data['formset'] = VersionFormset()
        return data

    def form_valid(self, form):
        """
        Валидация
        Проверка на несколько текущих версий
        """
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            instances = formset.save(commit=False)
            check_update = [instance for instance in instances]
            for item in formset.queryset:
                if item not in check_update:
                    check_update.append(item)
            check_current = [item for item in check_update if item.is_current]
            if len(check_current) > 1:
                form.add_error(None, "Может быть только одна версия!")
                return self.form_invalid(form)
            else:
                form.instance.user = self.request.user
                self.object = form.save()
                formset.instance = self.object
                formset.save()
                return super().form_valid(form)
        return super().form_invalid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('user:login')
    model = Product
    success_url = reverse_lazy('catalog:products')


class SuccessDeleteTemplateView(TemplateView):
    template_name = 'catalog/success_delete_product.html'


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('user:login')
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            data['formset'] = VersionFormset(instance=self.object)
        return data

    def form_valid(self, form):
        """
        Валидация
        Проверка на несколько текущих версий
        """
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            instances = formset.save(commit=False)
            check_update = [instance for instance in instances]
            for item in formset.queryset:
                if item not in check_update:
                    check_update.append(item)
            check_current = [item for item in check_update if item.is_current]
            if len(check_current) > 1:
                form.add_error(None, "Может быть только одна версия!")
                return self.form_invalid(form)
            else:
                formset.instance = self.object
                formset.save()
                return super().form_valid(form)
        return super().form_invalid(form)

    def get_form_class(self):
        user = self.request.user
        moderator_permissions = [
            user.has_perm("catalog.set_published"),
            user.has_perm("catalog.edit_description"),
            user.has_perm("catalog.change_category_product")
        ]
        if self.object.user == user:
            return ProductForm
        if all(moderator_permissions):
            return ModeratorProductForm
        raise PermissionDenied


class SuccessAddProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/success_adding_product.html'

catalog/templates/catalog/add_product.html
{% extends "catalog/base.html" %}
{% block title %}Contacts{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% if warning_text %}
        <div class="col-md-12">
            <div class="alert alert-warning" role="alert">
                {{ warning_text }}
            </div>
        </div>
        {% endif %}
        <div class="bg-body-tertiary p-4 rounded">
            <div class="container my-3">
                <form class="row g-3" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-md-12">
                        <label for="selectCategory" class="form-label">Выбрать категорию</label>
                        <select class="form-select" aria-label="Выбор категории" id="selectCategory" name="category">
                            {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-12">
                        <label for="inputProductName" class="form-label">Название</label>
                        <input type="text" class="form-control" id="inputProductName" name="product_name" required>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="formPhoto" class="form-label">Загрузите фотографии продукта</label>
                        <input class="form-control" name="product_image" type="file" id="formPhoto" multiple>
                    </div>
                    <div class="col-md-12">
                        <label for="textareaDescription" class="form-label">Описание</label>
                        <textarea class="form-control" id="textareaDescription" rows="6" name="product_description"
                                  required></textarea>
                    </div>
                    <div class="col-md-12">
                        <label for="inputPriceFrom" class="form-label">Цена</label>
                        <input type="text" class="form-control" id="inputPriceFrom" name="product_price" required>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary w-100 mt-4 mb-2">Добавить</button>
                    </div>
                </form>
                <div class="col-12">
                    <a class="btn btn-secondary w-100" href="{% url 'index' %}">Отмена</a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Online Store{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% block content %}{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block title %}Main Page{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% include 'catalog/includes/header_main.html' %}
        <div class="row m-4">
            {% for product in products %}
            <div class="p-2 rounded col-4">
                <div class="card m-4">
                    <img src="{% mymedia product.image  %}" class="card-img-top" alt="no_image">
                    <div class="card-body">
                        <h5>{{ product.name }}</h5>
                        <h1>{{ product.price }} руб.</h1>
                        <p class="card-text text-secondary"><small>пользователь: {{ product.user }}</small></p>
                        <p class="card-text">{{ product.description|slice:99 }}...</p>
                        <a href="{% url 'catalog:product' product.id %}" type="button" class="btn btn-primary">Открыть</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% include 'blog/includes/header_delete_blog.html' %}
        <div class="my-2">
            <div class="card border-warning mb-3 text-center">
                <div class="card-header">Вы точно хотите удалить?</div>
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.description|slice:":100" }}...</p>
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a class="btn btn-secondary" href="{% url 'catalog:product' object.pk %}">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% include 'catalog/includes/header_product.html' %}
        {% if object.user == user or perms.is_superuser or request.user|has_group:"moderator" %}
        <div class="btn-group btn-group-sm mt-2" role="group" aria-label="Basic mixed styles example">
            {% if not request.user|has_group:"moderator" %}
            <a href="{% url 'catalog:delete_product' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
            {% endif %}
            <a href="{% url 'catalog:update_product' object.pk %}" type="button" class="btn btn-secondary">Редактировать</a>
        </div>
        {% endif %}
        <div class="my-2">
            <div class="card mb-3" style="max-width: 100em;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{% mymedia object.image %}" class="img-fluid rounded-start"
                             alt="image for {{ product.name }}">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <span class="badge text-bg-secondary">{{ object.category.name }}</span>
                            <h3 class="card-title my-2">{{ object.name }}</h3>
                            <h1 class="card-title my-4">{{ object.price }} руб.</h1>
                            <div><strong>Пользователь:</strong> {{ object.user }}</div>
                            <div><strong>Описание:</strong> {{ object.description }}</div>
                            <p class="card-text">
                                <small class="text-body-secondary">добавлен: {{ object.created_at }}</small>
                            </p>
                            <button type="button" class="btn btn-outline-primary" disabled>Купить</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends "catalog/base.html" %}
{% block title %}Add Product{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        {% if warning_text %}
        <div class="col-md-12">
            <div class="alert alert-warning" role="alert">
                {% for text in warning_text %}
                <p><b>{{ text.0 }}:</b> {{ text.1 }}</p>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="bg-body-tertiary p-4 rounded">
            <div class="container my-3 col-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="container row">
                        <div class="col-6">
                            <h5 class="mb-3">Продукт</h5>
                            {{ form.as_p }}
                            <div class="row">
                                {% if object %}
                                <div class="col-6">
                                    <button type="submit" class="btn btn-primary mt-4 mb-2 w-100">Сохранить</button>
                                </div>
                                <div class="col-6">
                                    <a class="btn btn-secondary mt-4 mb-2 w-100"
                                       href="{% url 'catalog:product' object.pk %}">Отмена</a>
                                </div>
                                {% else %}
                                <div class="col-6">
                                    <button type="submit" class="btn btn-primary mt-4 mb-2 w-100">Добавить</button>
                                </div>
                                <div class="col-6">
                                    <a class="btn btn-secondary mt-4 mb-2 w-100"
                                       href="{% url 'catalog:index' %}">Отмена</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-6 p-2  rounded">
                            <h5 class="mb-3">Версии продукта</h5>
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                            <div class="card m-2 p-2 rounded border bg-body-secondary">
                                {{ form.as_p }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/success_adding_product.html
{% extends "catalog/base.html" %}
{% block title %}Success adding product{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        <div class="bg-body-tertiary p-4 rounded">
            <div class="col-sm-8 py-4 mx-auto">
                <h2 class="display-5 fw-medium">Успешно добавлен продукт</h2>
                <div class="my-4">
                    <p><strong>Катеория: </strong>{{ object.category.name }}</p>
                    <p><strong>Название: </strong>{{ object.name }}</p>
                    <p><strong>Описание: </strong>{{ object.description }}</p>
                    <p><strong>Цена: </strong>{{ product.price }}</p>
                </div>
                <a href="{% url 'catalog:index' %}" type="button" class="btn btn-primary">Вернуться на главную страницу</a>
            </div>
        </div>
    </div>

</main>
{% endblock %}

catalog/templates/catalog/success_delete_product.html
{% extends "catalog/base.html" %}
{% block title %}Success adding product{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        <div class="bg-body-tertiary p-4 rounded">
            <div class="col-sm-8 py-4 mx-auto">
                <h2 class="display-5 fw-medium">Продукт удален</h2>
                <a href="{% url 'catalog:index' %}" type="button" class="btn btn-primary">Вернуться на главную страницу</a>
            </div>
        </div>
    </div>

</main>
{% endblock %}

catalog/templates/catalog/usercontacts_detail.html
{% extends "catalog/base.html" %}
{% block title %}Thanx{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        <div class="bg-body-tertiary p-4 rounded">
            <div class="col-sm-8 py-4 mx-auto">
                <h2 class="display-5 fw-medium">Thank You</h2>
                <div class="my-4">
                    <p>Уважаемый, <strong>{{ object.first_name }} {{ object.last_name }}</strong></p>
                    <p>Мы обязательно пришлем вам письмо на почту <strong>{{ object.email }}</strong></p>
                </div>
                <a href="{% url 'catalog:index' %}" type="button" class="btn btn-primary">Вернуться на главную страницу</a>
            </div>
        </div>
    </div>

</main>
{% endblock %}

catalog/templates/catalog/usercontacts_form.html
{% extends "catalog/base.html" %}
{% block title %}Contacts{% endblock %}
{% block content %}
<main>
    {% include 'catalog/includes/navbar_include.html' %}
    <div class="container my-2">
        <div class="bg-body-tertiary p-4 rounded">
            <div class="col-sm-8 py-4 mx-auto">
                <h2 class="display-5 fw-medium">Contacts</h2>
                <div class="my-4">
                    {% for contact in contacts %}
                    <p>{{ contact.name }}: <strong>{{ contact.link }}</strong></p>
                    {% endfor %}
                </div>
                <div class="accordion accordion-flush py-4" id="accordionFlushExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#flush-collapseOne" aria-expanded="false"
                                    aria-controls="flush-collapseOne">
                                Свяжитесь со мной
                            </button>
                        </h2>
                        <div id="flush-collapseOne" class="accordion-collapse collapse"
                             data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="first_name" class="form-label">Имя</label>
                                        <input type="text" class="form-control" id="first_name"
                                               aria-describedby="emailHelp" name="first_name" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="last_name" class="form-label">Фамилия</label>
                                        <input type="text" class="form-control" id="last_name" name="last_name"
                                               aria-describedby="emailHelp" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="email" class="form-label">Email</label>
                                        <input type="email" class="form-control" id="email" name="email"
                                               aria-describedby="emailHelp" required>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Отправить</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}